version: "3"
services:
  server:
    build: .
    environment:
      - MONGOURI=mongodb://mongo/casasoft
    ports:
      - 3000:3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
    - "27017:27017"
